"""add model gallon, notification, ledger, information, bailout, driverGallon

Revision ID: 00a150f27cd5
Revises: 4073ebcd506b
Create Date: 2024-07-30 07:57:26.118155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a150f27cd5'
down_revision = '4073ebcd506b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_gallon',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_gallon', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_gallon_phone'), ['phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_driver_gallon_username'), ['username'], unique=False)

    op.create_table('bailout',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bailout', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bailout_image'), ['image'], unique=False)
        batch_op.create_index(batch_op.f('ix_bailout_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_bailout_title'), ['title'], unique=False)

    op.create_table('gallon',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('current', sa.Float(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('information',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_information_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_information_title'), ['title'], unique=False)

    op.create_table('ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_image'), ['image'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_ledger_title'), ['title'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('form_user', sa.BigInteger(), nullable=True),
    sa.Column('message', sa.String(length=120), nullable=True),
    sa.Column('to_user', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_user'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_message'), ['message'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_title'), ['title'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('avatar', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')
        batch_op.drop_column('role')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_title'))
        batch_op.drop_index(batch_op.f('ix_notification_message'))

    op.drop_table('notification')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_title'))
        batch_op.drop_index(batch_op.f('ix_ledger_message'))
        batch_op.drop_index(batch_op.f('ix_ledger_image'))

    op.drop_table('ledger')
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_information_title'))
        batch_op.drop_index(batch_op.f('ix_information_message'))

    op.drop_table('information')
    op.drop_table('gallon')
    with op.batch_alter_table('bailout', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bailout_title'))
        batch_op.drop_index(batch_op.f('ix_bailout_message'))
        batch_op.drop_index(batch_op.f('ix_bailout_image'))

    op.drop_table('bailout')
    with op.batch_alter_table('driver_gallon', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_gallon_username'))
        batch_op.drop_index(batch_op.f('ix_driver_gallon_phone'))

    op.drop_table('driver_gallon')
    # ### end Alembic commands ###
